server:
    address: 0.0.0.0
    port: 8080
    error:
        include-message: always
        include-binding-errors: always
spring:
    datasource:
        url: ${DB_URL}
        password: ${DB_PASSWORD}
        username: ${DB_USERNAME}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 2   # safe for free-tier
            minimum-idle: 1
            idle-timeout: 30000
            max-lifetime: 1800000
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                show_sql: true
    servlet:
        multipart:
            max-file-size: 10MB  # Sets the maximum size for a single file
            max-request-size: 10MB # Sets the maximum size for the entire request
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_SIGN_IN_CLIENT_ID}
                        client-secret: ${GOOGLE_SIGN_IN_CLIENT_SECRET}
                        scope: openid,profile,email
                    github:
                        client-id: ${GITHUB_SIGN_IN_CLIENT_ID}
                        client-secret: ${GITHUB_SIGN_IN_CLIENT_SECRET}
                        scope: user:email
                    
